
spring:
  application:
    name: Redisson-Worker-Service
  profiles:
    active: local
server:
    port: 8581

eureka:  instance:    instanceId: reactive.com:${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: false 
    secure-virtual-host-name: ${spring.application.name}
    health-check-url: http://localhost:8761/health
    lease-renewal-interval-in-seconds: 30
  client:    fetch-registry: true
    service-url:       defaultZone: http://localhost:8761/eureka/
    