
redisson:
    config: redissonWorkerNodeConfig-dev.yaml
    
eureka:
  instance:
    health-check-url: http://localhost:8761/health
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
  

