
redisson:
    config: redissonWorkerNodeConfig-docker.yaml

eureka:
  instance:
    # Give your eureka details
    health-check-url: 
  client:
    service-url:
       # Give your eureka details
       defaultZone: 